#### Install library if not installed

In [6]:
# ! pip install "numpy<2"
# ! pip install catboost
# ! pip install scikit-learn

#### Import Dependency

In [17]:
import numpy as np
import pandas as pd
from catboost import CatBoostClassifier, Pool
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
pd.set_option('display.max_columns', None)

#### Read dataset

In [11]:
df = pd.read_csv("/data/ksa/00_Data_Input/relabelled_data_ksa_explore.csv")

In [13]:
df[df.isna().any(axis=1)]

Empty DataFrame
Columns: [idpoint, idsubsegment, idsegment, nth, periode, observation, MGRS, VH_0, VH_1, VH_2, VH_3, VH_4, VH_5, VH_6, VH_7, VH_8, VH_9, VH_10, VH_11, VH_12, VH_13, VH_14, VH_15, VH_16, VH_17, VH_18, VH_19, VH_20, VH_21, VH_22, VH_23, VH_24, VH_25, VH_26, VH_27, VH_28, VH_29, VH_30, F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12, F13, F14, F15, F16, F17, class, bulan, tahun, idkab]
Index: []

[0 rows x 59 columns]

In [18]:
df.head()

,idpoint,idsubsegment,idsegment,nth,periode,observation,MGRS,VH_0,VH_1,VH_2,VH_3,VH_4,VH_5,VH_6,VH_7,VH_8,VH_9,VH_10,VH_11,VH_12,VH_13,VH_14,VH_15,VH_16,VH_17,VH_18,VH_19,VH_20,VH_21,VH_22,VH_23,VH_24,VH_25,VH_26,VH_27,VH_28,VH_29,VH_30,F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,F11,F12,F13,F14,F15,F16,F17,class,bulan,tahun,idkab
0,320101008b1#01,320101008b1,320101008,9,2022_30,6.0,48MYU,-1387,-1368,-1351,-1317,-1300,-1265,-1201,-1233,-1296,-1254,-1169,-998,-864,-931,-1065,-1108,-1194,-1365,-1352,-1332,-1342,-1362,-1396,-1464,-1532,-1577,-1630,-1680,-1647,-1580,-1446,-1387,-1387,-1201,0,6,-1680,-864,816,3,-18.9999999999,-1.5182132651836786,1.000000,0.785398,-31.000000,-1.538549,-217.9999999999,-1.5662092030054973,NP,9,2022,3201
1,320101008b1#01,320101008b1,320101008,10,2023_03,6.0,48MYU,-1434,-1415,-1377,-1396,-1387,-1368,-1351,-1317,-1300,-1265,-1201,-1233,-1296,-1254,-1169,-998,-864,-931,-1065,-1108,-1194,-1365,-1352,-1332,-1342,-1362,-1396,-1464,-1532,-1577,-1630,-1434,-1434,-1265,0,9,-1680,-864,816,3,-18.9999999999,-1.5182132651836786,1.000000,0.785398,-18.777778,-1.517592,-232.9999999999,-1.5665045076528836,NP,10,2023,3201
2,320101008b2#01,320101008b2,320101008,4,2022_18,6.0,48MYU,-948,-1098,-1398,-1198,-1291,-1476,-1442,-1374,-1340,-1356,-1388,-1451,-1519,-1564,-1639,-1788,-1887,-1821,-1689,-1621,-1587,-1604,-1594,-1574,-1534,-1454,-1294,-1153,-870,-648,-759,-948,-1476,-948,5,0,-1887,-648,1239,4,150.0000000001,1.5641297588910328,105.600000,1.561327,1.000000,0.785398,440.0000000001,1.5685236034352557,NP,4,2022,3201
3,320101008b2#01,320101008b2,320101008,5,2022_20,5.0,48MYU,-1424,-1248,-948,-1098,-1398,-1198,-1291,-1476,-1442,-1374,-1340,-1356,-1388,-1451,-1519,-1564,-1639,-1788,-1887,-1821,-1689,-1621,-1587,-1604,-1594,-1574,-1534,-1454,-1294,-1153,-870,-1424,-1476,-948,7,2,-1887,-648,1239,4,-175.9999999999,-1.5651145697540458,7.428571,1.436985,-238.000000,-1.566595,-83.9999999999,-1.5588921272365726,PL,5,2022,3201
4,320101008b2#01,320101008b2,320101008,12,2023_07,6.0,48MYU,-1479,-1438,-1356,-1397,-1478,-1532,-1496,-1424,-1388,-1370,-1378,-1393,-1423,-1443,-1482,-1541,-1658,-1580,-1424,-1248,-948,-1098,-1398,-1198,-1291,-1476,-1442,-1374,-1340,-1356,-1388,-1479,-1532,-1356,5,2,-1658,-948,710,4,-40.9999999999,-1.5464109176221186,10.600000,1.476735,-61.500000,-1.554538,-100.9999999999,-1.5608956602068982,NP,12,2023,3201

In [ ]:
# Initialize the CatBoostClassifier
model = CatBoostClassifier(iterations=100,
                           learning_rate=0.1,
                           depth=6,
                           verbose=0)

# Train the model
model.fit(X_train, y_train)